### ISSUE TITLE
Data being stored in s3 has a bytestring in it, which will likely cause issues

### ISSUE THREAD

**Issue by knoxsp** [pywr/hydra-pywr#35]
Data being stored now looks like this:

{
	"data": {
		"url": "s3://pywr-results/b'\\x89\\xa2T\\r\\xff\\x0cB5\\xaf\\xa2\\xf0\\x94`/%\\x9d6\\xbb>\\xa1\\xa4\\xfc\\xebss\\xaf\\\\\\xfe\\xb28\\xba)'/simulated_volume.h5",
		"group": "YavanDam"
	}
}

Notice that the ID has a byttestring in it, instead of a standard string. This should be changed to be more decipherable.

**Comment by pmslavin** [comment]
This is coming from the `hmac.digest` on L160...

```python
    hashkey = hashlib.sha256(randbytes(56)).hexdigest().encode('utf-8')
    self.s3_path = hmac.digest(hashkey, str(self.scenario_id).encode('utf-8'), hashlib.sha256
```

So if a string of some hex is acceptable we can just call `.hex()` on the bytes instance it returns.  The url above would become...
```
s3://pywr-results/89a2540dff0c4235afa2f094602f259d36bb3ea1a4fceb7373af5cfeb238ba29/simulated_volume.h5
```

**Comment by knoxsp** [comment]
Looks good. Can you put that in a suggestion?

**Comment by pmslavin** [comment]
Added this on the branch [here](https://github.com/pywr/hydra-pywr/blob/b906bbf8b71f6e2ed6c9706461e49332b28f2fe0/hydra_pywr/runner.py#L160).

Both the uses of `s3_path` after that (L314, L712) are as strings so no-longer being bytes should be fine.
